### ISSUE TITLE
GP vs. biweight

### ISSUE THREAD

**Issue by MilevaE** [hippke/wotan#29]
Hi, 
this is not really an issue, it just an usage concern.
I have been exploring different algorithms of WOTAN, and I notice that biweight algorithm yield almost the same result than a GP (whatever kernel) but much more faster. Then, my question is about why use a GP model? is somehow better?  

thanks in advance!

**Comment by hippke** [comment]
I Mileva,
Thank you for your question.
- Similarity: Indeed, often the trends calculated with various methods are very similar (but usually not identical). Small differences may be irrelevant in some cases, but dramatic in other cases. The differences become more pronounced with non-Gaussian noise. Try it yourself!
- Speed: Most algorithms are very fast for small datasets (1000 points or less) but have very different scalings for more data. For 100k points, for examples, GPs will be extremly slow, but the biweight should still be fine.
- What algorithm to use? See [xkcd](https://xkcd.com/2048/). It depends on your data and goal. As we write in the paper, you should try various method and see which gives the best result for your specific purpose. For blind transit searches, it might be the biweight and not GPs. For other purposes, who knows? Try it out!

**Comment by MilevaE** [comment]
Can't be better explained! thanks a lot!!
