### ISSUE TITLE
Computation of the RMS of a given lightcuve

### ISSUE THREAD

**Issue by MilevaE** [hippke/wotan#47]
Hi, 

I was wondering if there is any way with WOTAN to compute the RMS let's say from TESS data. 
If yes, should this be computed before or after detrended ?

Thanks!

**Comment by hippke** [comment]
Hi Mileva, typically RMS is calculated after the subtraction of a suitable trend. If you do it on the raw data, you risk to include instrumental systematics. That could be useful for certain cases, but mostly people want to understand the remaining noise after detrending.
When you have the flattened data, you can simply take the standard deviation of that, either for the full dataset, or for a segment (often people like to look at 6hr bins).

**Comment by MilevaE** [comment]
Thanks a lot Hippke!
