### ISSUE TITLE
Kernel size

### ISSUE THREAD

**Issue by MilevaE** [hippke/wotan#48]
Hi! 
which is the physical meaning of the kernel-size that have to be chosen when using a GP model? 

```
from wotan import flatten
flatten_lc1, trend_lc1 = flatten(time, flux, kernel_size=5, return_trend=True, method='gp', kernel='matern')
```

Not sure how to use this GP model correctly, or how to make it as much efficient as possible..

Thanks!

**Comment by hippke** [comment]
It's supposed to be approximately in units of days. If you really want to use GPs, I recommend a dedicated package such as celerite.

**Comment by MilevaE** [comment]
Thanks a lot!
