### ISSUE TITLE
'MaskedArray' object not callable

### ISSUE THREAD

**Issue by MilevaE** [hippke/wotan#50]
I'm trying to perform a process as follows: 

> Detrend (WOTAN)--> search and find a signal (TLS) --> set a mask corresponding to the planetary signal in the original data and detrend again (WOTAN)  --> search for a second signal (TLS) --> etc. 

The point is that my pipeline explores several detrends searching for the best one (maximize the SNR SDE etc.). Once a planet has been detected, I would like to remove it from the raw data and detrend again (exploring several options) previous the next search. I would like to use the raw data in this second step instead of the already detrended just to be sure that my next choice of best detrend model is not affected by the existence of the first planet. Unfortunately, I have this error: 

> flatten_lc, trend_lc  = flatten(time_second_run, flatten_second_run, method='gp', kernel='matern', kernel_size=wl[i], return_trend=True, break_tolerance=0.5)
> TypeError: 'MaskedArray' object is not callable

 does it mean I can not set a mask in the data that will be read in `flatten` command? if yes, is there any way to solve? 

Thanks a lot!

**Comment by hippke** [comment]
Can you try something like this?
```
from transitleastsquares import transitleastsquares, cleaned_array
intransit = transit_mask(time, periods[no], 2 * tdurs[no], t0s[no])
flux[intransit] = numpy.nan
time_second_run, flatten_second_run = cleaned_array(time, flux)
flatten_lc, trend_lc = flatten(...)
```

**Comment by MilevaE** [comment]
Hi Hippke, 

thanks a lot for your answer. Unfortunately I have the same problem.. :( 

```
    #the mask is set on the raw data: 
    intransit = transit_mask(flux_clean.time, periods[a], 2*durations[a], tos[a])
    flux_clean.flux[intransit]=np.nan
    time_second_run, flatten_second_run = cleaned_array(flux_clean.time, flux_clean.flux)
    flatten_lc, trend_lc  = flatten(time_second_run, flatten_second_run, window_length=wl[i], return_trend=True, method='biweight',break_tolerance=0.5,edge_cutoff=wl_min)
```

And the error... 

> Traceback (most recent call last):
>   File "./spectess.py", line 377, in <module>
>     flatten_lc, trend_lc  = flatten(time_second_run, flatten_second_run, window_length=wl[i], return_trend=True, method='biweight',break_tolerance=0.5,edge_cutoff=wl_min)
> TypeError: 'MaskedArray' object is not callable
> 
 
Any other suggestion?

thanks in advance!

**Comment by hippke** [comment]
Mhm, can you provide a full code example where this happens?

**Comment by MilevaE** [comment]
Hi Hippke, 

I solved the problem importing WOTAN flatten and t14 funtions for second time just before to start the mask. Not sure why, but doing so works well. The part of the code which is doing this looks now as follows: 


```
a=SNR.argmax()  #check the maximum SNR

if (SNR[a] > 5 and SDE[a] > 10 and 
       FAP[a] < 1e-4):
    from transitleastsquares import cleaned_array
      
    #the mask is set on the raw data: 
    intransit = transit_mask(flux_clean.time, periods[a], 2*durations[a], tos[a])
    flux_clean.flux[intransit]=np.nan
    time_second_run, flatten_second_run = cleaned_array(flux_clean.time, flux_clean.flux)
    
    from wotan import flatten
    from wotan import t14   
    
    #we repite the detrended process performed in the run 1
    if det_met == 2:
        wl_min=1    
        wl_max=12  
        wl_step=(wl_max-wl_min)/N_detrends 
        wl=np.arange(wl_min,wl_max,wl_step) # we define all the posibles window_length that we apply
        global_flatten_lc=np.zeros((len(wl),len(flatten_second_run)))
        global_trend_lc=np.zeros((len(wl),len(flatten_second_run)))
        for i in range(0,len(wl)):
            flatten_lc, trend_lc  = flatten(time_second_run, flatten_second_run, method='gp', kernel='matern', kernel_size=wl[i], return_trend=True, break_tolerance=0.5)
            global_flatten_lc[i]=flatten_lc
            global_trend_lc[i]=trend_lc
    else: 
        tdur=t14(R_s=radius, M_s=mass,P=P_protec,small_planet=True) #we define the typical duration of a small planet in this star 
        wl_min=3*tdur #minimum transit durantion 
        wl_max=20*tdur #maximum transit duration
        wl_step=(wl_max-wl_min)/N_detrends 
        wl=np.arange(wl_min,wl_max,wl_step) # we define all the posibles window_length that we apply 
        global_flatten_lc=np.zeros((len(wl),len(flatten_second_run)))
        global_trend_lc=np.zeros((len(wl),len(flatten_second_run)))
        for i in range(0,len(wl)):
            flatten_lc, trend_lc  = flatten(time_second_run, flatten_second_run, window_length=wl[i], return_trend=True, method='biweight',break_tolerance=0.5,edge_cutoff=wl_min)
            global_flatten_lc[i]=flatten_lc
            global_trend_lc[i]=trend_lc
```

Thanks a lot for your help! 

I close the issue, but please, add something else if you think I'm doing something wrong or not accurate.
