### ISSUE TITLE
time system offset bug

### ISSUE THREAD

**Issue by lgbouma** [hippke/wotan#51]
Hi Michael,

Thank you for writing and maintaining this software! It's very useful.

I believe I've found a bug (or at least, an undesirable behavior). The images and code below are an example. If the input time vector is in true BJD (with the 2457000, or whatever larger number prepended to it), the resulting fit shows a wonky chopping pattern. If the input time vector is median-subtracted, or has the offset removed, the detrending works as expected.

I'm not entirely sure _why_ this is happening. However it's easy enough to fix. Possible remedies might include:
* Updating the docstrings in the API to clarify that a median or mean-subtracted time vector in days is expected.
* Doing the reference time subtraction within the `flatten` module to whatever time vectors are passed.

Thanks again for your support!

Code to reproduce the bug, shown in images below:
https://github.com/lgbouma/cdips/blob/0cf37cb2b592a039623304e2a8e800c0b8a2809e/tests/test_wotan.py

Buggy behavior:
![test_wotan_fake_data_t0_2457000](https://user-images.githubusercontent.com/13185735/74764514-da80f580-524f-11ea-83fb-aa29f72a3aab.png)

Correct behavior with buggy chopping gone:
![test_wotan_fake_data_t0_0](https://user-images.githubusercontent.com/13185735/74764512-d9e85f00-524f-11ea-87b5-b0e3c7c44cff.png)

**Comment by hippke** [comment]
Thank you for the bug report! Are you using the latest version? A similar bug was fixed in 1.05 https://github.com/hippke/wotan/releases/tag/v1.0.5

**Comment by lgbouma** [comment]
Eep -- I was not. Apologies for missing this, and thank you for this response!
