### ISSUE TITLE
ImportError: Could not import pygam & supersmoother

### ISSUE THREAD

**Issue by 3fon3fonov** [hippke/wotan#53]
Dear Michael,

First of all, thanks a lot for "wotan"! I am very pleased to find that such a package exists! It is exactly what I was looking for some time for my Exo-Striker GUI tool. I am still exploring the "wotan" options but so far it seems that "wotan" works great in combination with the Exo-Striker. Here is a GUI of "wotan" within the Exo-Striker:

![wotan_example](https://user-images.githubusercontent.com/44244057/78768241-f53c3480-798b-11ea-936e-13d99b23cd54.png)

However, I encountered two problems. When I try "pspline", I am getting:

```
 File "/usr/local/lib/python3.6/dist-packages/wotan/flatten.py", line 293, in flatten
    time_view, flux_view, edge_cutoff, max_splines, return_nsplines, verbose
", line 11, in pspline
    raise ImportError('Could not import pygam')
ImportError: Could not import pygam
')
ImportError: Could not import pygam
```

while trying "supersmoother" :

```
  File "/usr/local/lib/python3.6/dist-packages/wotan/flatten.py", line 253, in flatten
    raise ImportError('Could not import supersmoother')
ImportError: Could not import supersmoother
```

Any ideas what is going on? I tried Python 2 and 3, the same problem.

I installed via:
"pip2 install wotan" (Py2) and, with "pip3 install wotan" (Py3)

**Comment by hippke** [comment]
To install all additional dependencies, type
pip install statsmodels sklearn supersmoother pygam

**Comment by 3fon3fonov** [comment]
Thanks!

Yes, installing these fixed the problem. But I thought that any additional dependencies
should be automatically installed when we "pip install wotan", no? I would suggest to include these in the setup.py/pip installer.

BTW,  "pspline" computes prity slow w.r.t. "rspline", "hspline" and others.

**Comment by hippke** [comment]
Some people reported issues with these packages so I made it optional. Not sure what's the best solution.
Yes, `pspline` is 10-100x slower than other splines because it iterates over a range of knot distances to select the "best".

**Comment by 3fon3fonov** [comment]
OK, all clear! Thanks for all the help, I am closing.
