### ISSUE TITLE
finance example - returning nan

### ISSUE THREAD

**Issue by andrewczgithub** [hippke/wotan#54]
Hi @hippke !!

I hope your well.

I am trying a basic finance example but I am getting strange ressults.

I am using the below code -

' ' 'python
import yfinance as yf
import numpy as np
data = yf.download("AAPL", start="2017-01-01", end="2017-04-30")

price_series=data['Close'].to_numpy()
X_nasa = np.linspace(0,100, len(price_series))

from wotan import flatten
flatten_lc, trend_lc = flatten(X_nasa, price_series, window_length=10, return_trend=True)

trend_lc

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set()
import pandas as pd

q=pd.DataFrame(trend_lc)
r=pd.DataFrame(price_series)
q.plot()
r.plot()
' ' '

In your proffesional opinion would i be using the correct filter on the above?

Kind regards and thanks!
Andrew

**Comment by hippke** [comment]
It appears you have mixed up your variables. This works:

```
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from wotan import flatten

data = yf.download("AAPL", start="2017-01-01", end="2017-04-30")
price_series = data['Close'].to_numpy()
X_nasa = np.linspace(0, 100, len(price_series))
flatten_lc, trend_lc = flatten(
  X_nasa,
  price_series,
  window_length=10,
  method="hspline",
  return_trend=True
  )
plt.scatter(X_nasa, price_series, color='black')
plt.plot(X_nasa, trend_lc)
plt.show()

plt.scatter(X_nasa, flatten_lc)
plt.show()
```

**Comment by andrewcztrack** [comment]
thank you so much!!
much appreciate :)
