### ISSUE TITLE
pspline: Value error possibly triggered by gaps smaller than break tolerance

### ISSUE THREAD

**Issue by rachelbf** [hippke/wotan#57]
I get these errors for certain lightcurves (e.g.: 357898147, 45059728) that have gaps in them that (I can visually see) are smaller than the break tolerance. The only time that this error goes away is if I set break_tolerance = 0 which leads it to fit the data downlink gaps in the sectors as well. 
![Screen Shot 2020-09-29 at 13 36 06](https://user-images.githubusercontent.com/48811452/94613327-4a7d4280-0259-11eb-9aca-587d5b2e761e.png)

**Comment by hippke** [comment]
Can you provide a data file (or code that pulls the data) to reproduce?

**Comment by rachelbf** [comment]
Attached are two lightcurves (psf; extracted using eleanor) that are caused this error
[tic340003212.txt](https://github.com/hippke/wotan/files/5320230/tic340003212.txt)
[tic469811127.txt](https://github.com/hippke/wotan/files/5320231/tic469811127.txt)

**Comment by hippke** [comment]
Thank you for the bug report and sorry you're having issues with wotan.
I made a fix in [this file](https://github.com/hippke/wotan/blob/master/wotan/pspline.py). It now works for your example files. Can you check if more extensively and let me know if it works in all cases? I would then push a new wotan version to pip.

**Comment by rachelbf** [comment]
I tested it on about 10 light curves with that initially gave me the same error as above. With the fix, I don't get the error anymore.

**Comment by hippke** [comment]
Thanks for testing! Relased via pip and [github](https://github.com/hippke/wotan/releases/tag/v1.9).
