### ISSUE TITLE
OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by jordibp99** [hippke/wotan#58]
I wanted to work with an astro-software called exostriker which relies on numba. I've already downloades all the porgram with the necessary modules but when I try to execute it, an error appears:

OSError: Could not load shared object file: libllvmlite.so

Talking with the creator of the software, he has suggested it may be some type of error with numba as when I try to import the library in python I get the following error:

In [1]: import wotan
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-e7c7db287cef> in <module>
----> 1 import wotan

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/__init__.py in <module>
      1 from __future__ import division, print_function
      2 from wotan.t14 import t14
----> 3 from wotan.flatten import flatten
      4 from wotan.slide_clipper import slide_clip
      5 from wotan.helpers import transit_mask

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/flatten.py in <module>
     10 # wotan
     11 import wotan.constants as constants
---> 12 from wotan.cofiam import detrend_cofiam, detrend_cosine
     13 from wotan.gp import make_gp
     14 from wotan.huber_spline import detrend_huber_spline

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/cofiam.py in <module>
      1 from __future__ import print_function, division
----> 2 from numba import jit
      3 import numpy as np
      4 import wotan.constants as constants
      5 

~/.local/lib/python3.6/site-packages/numba/__init__.py in <module>
      9 import warnings
     10 
---> 11 from . import config, errors, _runtests as runtests, types
     12 
     13 # Re-export typeof

~/.local/lib/python3.6/site-packages/numba/config.py in <module>
     17 
     18 
---> 19 import llvmlite.binding as ll
     20 
     21 IS_WIN32 = sys.platform.startswith('win32')

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/__init__.py in <module>
      2 Things that rely on the LLVM library
      3 """
----> 4 from .dylib import *
      5 from .executionengine import *
      6 from .initfini import *

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/dylib.py in <module>
      1 from ctypes import c_void_p, c_char_p, c_bool, POINTER
      2 
----> 3 from llvmlite.binding import ffi
      4 from llvmlite.binding.common import _encode_string
      5 

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/ffi.py in <module>
    151         break
    152 else:
--> 153     raise OSError("Could not load shared object file: {}".format(_lib_name))
    154 
    155 

OSError: Could not load shared object file: libllvmlite.so

The same error as before. I wonder what it may be happening.

**Comment by hippke** [comment]
Seems to be a faulty numba/ missing llvm installation on Windows. Can you try in an unrelated script: import numba
```from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0.0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))
