### ISSUE TITLE
Recommended trend removal

### ISSUE THREAD

**Issue by andrewcztrack** [hippke/wotan#59]
Hi @hippke !!

I hope your well.

I was wondering if I could get some thoughts on using the package for financial time series.

I was planning on using  -

  window_length=15, return_trend=True, method='biweight'

Would the above be the method you recommend.

Best,
Andrew

**Comment by hippke** [comment]
Hi @andrewcztrack 
As beautifully shown by [Benoit Mandelbrot](https://en.wikipedia.org/wiki/Benoit_Mandelbrot), stock prices are non-Gaussian. If you want to remove long-term trends, it is advisable to use a detrending method which takes this into account. A good starting point would be wotan's default _biweight_ filter. As for the window_length, you really need to test what works for your data at hand. Can you share a data file and a few plots? Then I can have a closer look and say more about it.

**Comment by andrewcztrack** [comment]
Hi @hippke great to hear from you!
Basically the plan was to take out the trends before converting the price series to a return series.
observe some sample data below --
pricing data-
```python
import yfinance as yf
data = yf.download("QUAL.AX, QLTY.AX, VGS.AX, VAS.AX, VAE.AX, VISM.AX", start="2019-01-01", end="2020-12-30")['Adj Close']..dropna()
```
```python
return data -
data = yf.download("QUAL.AX, QLTY.AX, VGS.AX, VAS.AX, VAE.AX, VISM.AX", start="2019-01-01", end="2020-12-30")['Adj Close'].pct_change().dropna()
```

import yfinance as yf

**Comment by hippke** [comment]
With `window_length=20` I get something like this:
![Figure_1](https://user-images.githubusercontent.com/11958117/98982639-fd5ee280-251f-11eb-9cf8-82b09969444e.png)

Which trends should be removed, which should be kept? In astrophysics, you want to remove stellar noise and keep planetary transit signals. In finance, I guess it depends on your idea?
