### ISSUE TITLE
Detrending removes transits for data using a smaller cadences (than 30 min)

### ISSUE THREAD

**Issue by nicholasjannsen** [hippke/wotan#66]
Dear developers, 

I'm seeing some strange effects when performing detrending on simulated data with a cadence of 25s (cf. the PLATO N-CAM cadence). Attached you find a plot of my simulation produced by PlatoSim (Jannsen+2024) where I inject a Jupiter-sized planet around a early F-type star with a orbital period of 100 days (i=0, e=0). When I used the general example from your tutorial: `Wotan interface -> Choosing the right window size`) the detrending is removing my transit even if I choose a very large window mask (much larger than `3*tdur`).

Here is what I do; I started calculating the transit duration using
```
import wotan
from scipy import constants as c

tdur = wotan.t14(R_s=1.6, M_s=1.7, P=100, small_planet=False)
```
which given `tdur = 0.53 days` and  `3*tdur=1.59 days` which agrees well with my own calculations. I the use the following call to perform the detrending:
```
flatten_lc = flatten(time, flux, window_length=3 * tdur*c.day, return_trend=True)
```
I get the plot attached, which clearly shows that the window length is inefficient. I could simple:
- increase the window size, however, the that defeats the purpose of trying to remove also the fast varying trends in my light curve. Note, I need to increase the window to around 30-50 days before it doesn't destroy the transit.
- include a mask, but we want the method to automated (since in principle we don't know where the transits are).

I would not expect the method to be dependent on the cadence, but maybe this assumption is wrong? I guess that all the tests and the tutorials are all based on 30min cadence Kepler data?  I made a small test binning my data to 30min and the detrending now looks good. A potential workaround I can think of, is to bin the raw data to 30 min and then interpolate the trend back to the cadence (but I'm not an expect on detrending and if this may introduce biases).

I'm using Wotan v. 1.10. Let me know if I need to provide the dataset that I'm showing here.

Thanks for your help!
Nicholas Jannsen

![wotan_detrending_issue](https://github.com/hippke/wotan/assets/36379445/013ec3ad-0da2-4a0a-afbc-accd269a6c8d)

**Comment by hippke** [comment]
Hey, that's weird. Can you provide the data and a minimal example to reproduce?

**Comment by hippke** [comment]
Also make sure that your time series is in units of days in the data you feed to wotan

**Comment by nicholasjannsen** [comment]
Hi again, sorry for the delay.. Indeed that was the problem, thanks a lot!
